[package]
name = "blog_os"
version = "0.1.0"
edition = "2018"

# During "cargo build" panics are avoided
[profile.dev]
panic = "abort"

# During "cargo build" --release panics are avoided
[profile.release]
panic = "abort"

[dependencies]
